<?php

namespace App\Entity;

use App\Enum\InsightSeverity;
use App\Enum\InsightStatus;
use App\Enum\InsightType;
use App\Repository\PlanningInsightRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Attribute\Context;
use Symfony\Component\Serializer\Attribute\Groups;
use Symfony\Component\Serializer\Normalizer\DateTimeNormalizer;

/**
 * Alert/insight generated by the AI schedule supervision module
 * (e.g. detected understaffing, conflicting breaks, overload on a slot).
 *
 * This entity is the integration point between the Symfony backend and the
 * AI micro-service (see ai-service/). The backend can either:
 *  - query the AI micro-service on demand (endpoint /api/ai/analyze),
 *  - or receive a webhook from the micro-service and persist the result here.
 */
#[ORM\Entity(repositoryClass: PlanningInsightRepository::class)]
#[ORM\Table(name: 'planning_insight')]
#[ORM\Index(columns: ['target_date'], name: 'idx_insight_target_date')]
class PlanningInsight
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['insight:read'])]
    private ?int $id = null;

    #[ORM\Column(length: 30, enumType: InsightType::class)]
    #[Groups(['insight:read'])]
    private InsightType $type;

    #[ORM\Column(length: 20, enumType: InsightSeverity::class)]
    #[Groups(['insight:read'])]
    private InsightSeverity $severity;

    #[ORM\ManyToOne(targetEntity: Site::class)]
    #[ORM\JoinColumn(name: 'site_id', nullable: true, onDelete: 'SET NULL')]
    #[Groups(['insight:read'])]
    private ?Site $site = null;

    #[ORM\Column(name: 'target_date', type: 'date_immutable')]
    #[Groups(['insight:read'])]
    #[Context([DateTimeNormalizer::FORMAT_KEY => 'Y-m-d'])]
    private \DateTimeImmutable $targetDate;

    #[ORM\Column(type: 'text')]
    #[Groups(['insight:read'])]
    private string $message;

    /**
     * Raw data returned by the AI micro-service (details, scores, computed
     * staffing, etc.), useful for auditing, debugging and a future advanced UI.
     *
     * @var array<string, mixed>|null
     */
    #[ORM\Column(type: 'json', nullable: true)]
    #[Groups(['insight:read'])]
    private ?array $payload = null;

    #[ORM\Column(length: 20, enumType: InsightStatus::class)]
    #[Groups(['insight:read', 'insight:write'])]
    private InsightStatus $status = InsightStatus::NOUVELLE;

    #[ORM\Column]
    #[Groups(['insight:read'])]
    private \DateTimeImmutable $createdAt;

    public function __construct(InsightType $type, InsightSeverity $severity, \DateTimeImmutable $targetDate, string $message)
    {
        $this->type = $type;
        $this->severity = $severity;
        $this->targetDate = $targetDate;
        $this->message = $message;
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): InsightType
    {
        return $this->type;
    }

    public function getSeverity(): InsightSeverity
    {
        return $this->severity;
    }

    public function getSite(): ?Site
    {
        return $this->site;
    }

    public function setSite(?Site $site): static
    {
        $this->site = $site;

        return $this;
    }

    public function getTargetDate(): \DateTimeImmutable
    {
        return $this->targetDate;
    }

    public function getMessage(): string
    {
        return $this->message;
    }

    /** @return array<string, mixed>|null */
    public function getPayload(): ?array
    {
        return $this->payload;
    }

    /** @param array<string, mixed>|null $payload */
    public function setPayload(?array $payload): static
    {
        $this->payload = $payload;

        return $this;
    }

    public function getStatus(): InsightStatus
    {
        return $this->status;
    }

    public function setStatus(InsightStatus $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }
}
