<?php

namespace App\Enum;

/**
 * Types of alerts generated by the AI schedule supervision module.
 */
enum InsightType: string
{
    case SOUS_EFFECTIF = 'SOUS_EFFECTIF';
    case SURCHARGE = 'SURCHARGE';
    case CONFLIT_PAUSE = 'CONFLIT_PAUSE';
    case ANOMALIE_PLANNING = 'ANOMALIE_PLANNING';
    case AUTRE = 'AUTRE';
}
